env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-essential
  - "@nuxtjs/eslint-config-typescript"
  - "prettier"

plugins:
  - "@typescript-eslint"
  - vue
